windowrulev2 = suppressevent maximize, class:.*
# layerrule = blur on, match:namespace ^quickshell$
# layerrule = blur on, match:namespace ^quickshell:powerpanel$
windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(steam)$
windowrulev2 = float, class:^(yad)$
windowrulev2 = float, title:^Wallpaper\s+Picker$

layerrule {
  name = blur_shell
  blur = on
  match:namespace = quickshell
}

layerrule {
  name = blur_shell_power_panel
  blur = on 
  match:namespace = quickshell:powerpanel
}

# layerrule {
#   name = blur_shell_app_launcher
#   blur = on
#   match:namespace = quickshell:applauncher
# }
